/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiador.signals;

import estudiador.common.Coordenate;
import estudiador.screens.PantallaSignal;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Devas
 */
public class DiscreteSignal extends javax.swing.JPanel {
    SignalSum parentPanel;
    ArrayList<Coordenate> signal;
    int type;
    /**
     * Creates new form DiscreteSignal
     */
    public DiscreteSignal(SignalSum parentPanel, int type) {
        initComponents();
        this.parentPanel = parentPanel;
        this.type = type;
        signal = (type==0 ? parentPanel.getSignalA():parentPanel.getSignalB());
        updateList();
    }
    private void updateList(){
        DefaultListModel listModel = new DefaultListModel();
        signal.forEach((s)-> listModel.addElement("["+(int)s.getX()+","+(int)s.getY()+"]"));
        lstSignal.setModel(listModel);
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstSignal = new javax.swing.JList<>();
        txtNewX = new javax.swing.JTextField();
        btnAddPoint = new javax.swing.JButton();
        lblPuntos = new javax.swing.JLabel();
        lblAgregar = new javax.swing.JLabel();
        txtNewY = new javax.swing.JTextField();
        lblBracket1 = new javax.swing.JLabel();
        lblBracket2 = new javax.swing.JLabel();
        lblComma = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(310, 162));
        setMinimumSize(new java.awt.Dimension(310, 162));

        jScrollPane1.setViewportView(lstSignal);

        btnAddPoint.setText("Agregar");
        btnAddPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPointActionPerformed(evt);
            }
        });

        lblPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos.setText("Puntos");

        lblAgregar.setText("Agregar punto");

        lblBracket1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBracket1.setText("[");

        lblBracket2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBracket2.setText("]");

        lblComma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblComma.setText(",");

        btnDelete.setText("Eliminar seleccionado");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(lblBracket1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNewX, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)
                                    .addComponent(lblComma, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNewY, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblBracket2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAddPoint))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(btnDelete))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblPuntos)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAgregar)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAddPoint)
                                    .addComponent(txtNewX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNewY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBracket1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBracket2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblComma, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPointActionPerformed
        // TODO add your handling code here:
        String x = txtNewX.getText();
        String y = txtNewY.getText();
        if(x.isBlank() && y.isBlank()){
            x="0";
            y="0";
        }
        signal.add(new Coordenate(Integer.parseInt(x),Integer.parseInt(x)));
        updateList();
        if (type==0) this.parentPanel.setSignalA(signal);
        else this.parentPanel.setSignalB(signal);
        parentPanel.updatePlot();
    }//GEN-LAST:event_btnAddPointActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        signal.remove(lstSignal.getSelectedIndex());
        updateList();
        if (type==0) parentPanel.setSignalA(signal);
        else parentPanel.setSignalB(signal);
        parentPanel.updatePlot();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPoint;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgregar;
    private javax.swing.JLabel lblBracket1;
    private javax.swing.JLabel lblBracket2;
    private javax.swing.JLabel lblComma;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JList<String> lstSignal;
    private javax.swing.JTextField txtNewX;
    private javax.swing.JTextField txtNewY;
    // End of variables declaration//GEN-END:variables
}
