/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiador.signals;

import estudiador.screens.PantallaSignal;
import estudiador.screens.PantallaInicio;
import estudiador.screens.StartScreen;
import static java.lang.System.exit;

/**
 *
 * @author Devas
 */
public class NavMenu extends javax.swing.JPanel {
    StartScreen parentFrame;
    /**
     * Creates new form NavMenu
     */
    public NavMenu(StartScreen parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCanvas = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnEjemplo = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnBackMenu = new javax.swing.JButton();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        setMaximumSize(new java.awt.Dimension(980, 45));
        setMinimumSize(new java.awt.Dimension(980, 45));
        setPreferredSize(new java.awt.Dimension(980, 45));

        btnCanvas.setText("Terminar");
        btnCanvas.setToolTipText("");
        btnCanvas.setActionCommand("btnCanvas");
        btnCanvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanvasActionPerformed(evt);
            }
        });

        btnSumar.setText("Sumar");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnEjemplo.setText("Ejemplo");
        btnEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjemploActionPerformed(evt);
            }
        });

        btnQuiz.setText("Estudiar");
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        btnBackMenu.setText("Regresar");
        btnBackMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btnCanvas)
                .addGap(101, 101, 101)
                .addComponent(btnSumar)
                .addGap(97, 97, 97)
                .addComponent(btnEjemplo)
                .addGap(91, 91, 91)
                .addComponent(btnQuiz)
                .addGap(189, 189, 189)
                .addComponent(btnBackMenu)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCanvas)
                    .addComponent(btnSumar)
                    .addComponent(btnEjemplo)
                    .addComponent(btnQuiz)
                    .addComponent(btnBackMenu))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjemploActionPerformed
        // TODO add your handling code here:
        parentFrame.insertContent(new PantallaSignal(parentFrame));
    }//GEN-LAST:event_btnEjemploActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        // TODO add your handling code here:
         parentFrame.insertContent(new SignalSum(parentFrame));
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnCanvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanvasActionPerformed
        // TODO add your handling code here:
         exit(0);
    }//GEN-LAST:event_btnCanvasActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        // TODO add your handling code here:
         parentFrame.insertContent(new QuizSignal(parentFrame));
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnBackMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackMenuActionPerformed
        // TODO add your handling code here:
         parentFrame.insertContent(new PantallaInicio(parentFrame));
    }//GEN-LAST:event_btnBackMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackMenu;
    private javax.swing.JButton btnCanvas;
    private javax.swing.JButton btnEjemplo;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnSumar;
    // End of variables declaration//GEN-END:variables
}
