/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiador.signals;

import estudiador.common.ImageHandler;
import estudiador.common.Question;
import estudiador.common.QuestionBox;
import estudiador.common.SoundHandler;
import estudiador.screens.StartScreen;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Devas
 */
public class QuizSignal extends javax.swing.JPanel {
    StartScreen parentFrame;
    QuestionBox qBox;
    Question showingQ;
    /**
     * Creates new form QuizSignal
     */
    public QuizSignal(StartScreen parentFrame) {
        this.parentFrame = parentFrame;
        qBox = new QuestionBox("./contentFiles/Signals.csv");
        initComponents();
        addMenu();
        makeQuestion();
    }
    
    private void makeQuestion(){
        showingQ = qBox.getRandomQ();
        pnOpt0.setLayout(new BorderLayout());
        pnOpt1.setLayout(new BorderLayout());
        pnOpt2.setLayout(new BorderLayout());
        pnOpt3.setLayout(new BorderLayout());
        lblPreguntaText.setText(showingQ.getTitulo());
        pnOpt0.add(ImageHandler.getPaneImage("./contentFiles/SignalQuiz/"+showingQ.getOpcion(0).getImage()));
        pnOpt1.add(ImageHandler.getPaneImage("./contentFiles/SignalQuiz/"+showingQ.getOpcion(1).getImage()));
        pnOpt2.add(ImageHandler.getPaneImage("./contentFiles/SignalQuiz/"+showingQ.getOpcion(2).getImage()));
        pnOpt3.add(ImageHandler.getPaneImage("./contentFiles/SignalQuiz/"+showingQ.getOpcion(3).getImage()));
        rdbtnOp0.setText(showingQ.getOpcion(0).getText());
        rdbtnOp1.setText(showingQ.getOpcion(1).getText());
        rdbtnOp2.setText(showingQ.getOpcion(2).getText());
        rdbtnOp3.setText(showingQ.getOpcion(3).getText());
        repaint();
    }
    private void addMenu(){
        pnNavM.setLayout(new BorderLayout());
        pnNavM.removeAll();
        pnNavM.add(new NavMenu(parentFrame));
        this.validate();
        this.repaint();
    }
    private boolean calificarRespuesta(){
        int ans = showingQ.getAnswerIndex();
        switch(ans){
            case 0:
                if(rdbtnOp0.isSelected()) return true;
                break;
            case 1:
                if(rdbtnOp1.isSelected()) return true;
                break;
            case 2:
                if(rdbtnOp2.isSelected()) return true;
                break;
            case 3:
                if(rdbtnOp3.isSelected()) return true;
                break;
            default:
                break;
        }
        return false;
    }
    private void feedBack(){
        if(calificarRespuesta()){
           SoundHandler.playSound("./contentFiles/Sounds/correct.wav");
           JOptionPane.showMessageDialog(new JFrame(),
                "Felicidades, es CORRECTO!",
                "Mensaje de confirmación",
                JOptionPane.INFORMATION_MESSAGE,
                new ImageIcon(ImageHandler.getBuffImage("./contentFiles/Images/check.png")));
        }else{
            SoundHandler.playSound("./contentFiles/Sounds/incorrect.wav");
            JOptionPane.showMessageDialog(new JFrame(),
                "Incorrecto",
                "Mensaje de confirmación",
                JOptionPane.ERROR_MESSAGE);
        }
        makeQuestion();
    }
    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpOpciones = new javax.swing.ButtonGroup();
        lblTitleSig = new javax.swing.JLabel();
        pnNavM = new javax.swing.JPanel();
        pnQuestion = new javax.swing.JPanel();
        pnQuestionTitle = new javax.swing.JPanel();
        lblPreguntaText = new javax.swing.JLabel();
        spTitle = new javax.swing.JSeparator();
        pnOptions = new javax.swing.JPanel();
        pnOpt1 = new javax.swing.JPanel();
        pnOpt2 = new javax.swing.JPanel();
        pnOpt0 = new javax.swing.JPanel();
        pnOpt3 = new javax.swing.JPanel();
        rdbtnOp0 = new javax.swing.JRadioButton();
        rdbtnOp1 = new javax.swing.JRadioButton();
        rdbtnOp2 = new javax.swing.JRadioButton();
        rdbtnOp3 = new javax.swing.JRadioButton();
        spOptions = new javax.swing.JSeparator();
        pnControls = new javax.swing.JPanel();
        btnCalificar = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1000, 680));

        lblTitleSig.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblTitleSig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSig.setText("Módulo de Señales");

        pnNavM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnNavM.setMaximumSize(new java.awt.Dimension(980, 45));
        pnNavM.setMinimumSize(new java.awt.Dimension(980, 45));
        pnNavM.setPreferredSize(new java.awt.Dimension(980, 45));

        javax.swing.GroupLayout pnNavMLayout = new javax.swing.GroupLayout(pnNavM);
        pnNavM.setLayout(pnNavMLayout);
        pnNavMLayout.setHorizontalGroup(
            pnNavMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        pnNavMLayout.setVerticalGroup(
            pnNavMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        pnQuestion.setMinimumSize(new java.awt.Dimension(980, 200));
        pnQuestion.setPreferredSize(new java.awt.Dimension(980, 400));
        pnQuestion.setLayout(new javax.swing.BoxLayout(pnQuestion, javax.swing.BoxLayout.PAGE_AXIS));

        pnQuestionTitle.setPreferredSize(new java.awt.Dimension(980, 50));
        pnQuestionTitle.setLayout(new java.awt.BorderLayout());

        lblPreguntaText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblPreguntaText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPreguntaText.setText("Seleccione la gráfica Sen(x)");
        pnQuestionTitle.add(lblPreguntaText, java.awt.BorderLayout.CENTER);
        pnQuestionTitle.add(spTitle, java.awt.BorderLayout.PAGE_START);

        pnOptions.setMinimumSize(new java.awt.Dimension(980, 100));
        pnOptions.setPreferredSize(new java.awt.Dimension(980, 300));

        pnOpt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnOpt1.setMaximumSize(new java.awt.Dimension(200, 141));
        pnOpt1.setMinimumSize(new java.awt.Dimension(200, 141));
        pnOpt1.setPreferredSize(new java.awt.Dimension(200, 141));

        javax.swing.GroupLayout pnOpt1Layout = new javax.swing.GroupLayout(pnOpt1);
        pnOpt1.setLayout(pnOpt1Layout);
        pnOpt1Layout.setHorizontalGroup(
            pnOpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnOpt1Layout.setVerticalGroup(
            pnOpt1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnOpt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnOpt2.setMaximumSize(new java.awt.Dimension(200, 141));
        pnOpt2.setMinimumSize(new java.awt.Dimension(200, 141));
        pnOpt2.setPreferredSize(new java.awt.Dimension(200, 141));

        javax.swing.GroupLayout pnOpt2Layout = new javax.swing.GroupLayout(pnOpt2);
        pnOpt2.setLayout(pnOpt2Layout);
        pnOpt2Layout.setHorizontalGroup(
            pnOpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnOpt2Layout.setVerticalGroup(
            pnOpt2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        pnOpt0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnOpt0.setMaximumSize(new java.awt.Dimension(200, 141));
        pnOpt0.setMinimumSize(new java.awt.Dimension(200, 141));
        pnOpt0.setPreferredSize(new java.awt.Dimension(200, 141));

        javax.swing.GroupLayout pnOpt0Layout = new javax.swing.GroupLayout(pnOpt0);
        pnOpt0.setLayout(pnOpt0Layout);
        pnOpt0Layout.setHorizontalGroup(
            pnOpt0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );
        pnOpt0Layout.setVerticalGroup(
            pnOpt0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnOpt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnOpt3.setMaximumSize(new java.awt.Dimension(200, 141));
        pnOpt3.setMinimumSize(new java.awt.Dimension(200, 141));
        pnOpt3.setPreferredSize(new java.awt.Dimension(200, 141));

        javax.swing.GroupLayout pnOpt3Layout = new javax.swing.GroupLayout(pnOpt3);
        pnOpt3.setLayout(pnOpt3Layout);
        pnOpt3Layout.setHorizontalGroup(
            pnOpt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnOpt3Layout.setVerticalGroup(
            pnOpt3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btngrpOpciones.add(rdbtnOp0);
        rdbtnOp0.setText("op0");
        rdbtnOp0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btngrpOpciones.add(rdbtnOp1);
        rdbtnOp1.setText("op1");
        rdbtnOp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btngrpOpciones.add(rdbtnOp2);
        rdbtnOp2.setText("op2");
        rdbtnOp2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btngrpOpciones.add(rdbtnOp3);
        rdbtnOp3.setText("op3");
        rdbtnOp3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout pnOptionsLayout = new javax.swing.GroupLayout(pnOptions);
        pnOptions.setLayout(pnOptionsLayout);
        pnOptionsLayout.setHorizontalGroup(
            pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOptionsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnOpt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbtnOp0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnOpt1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(rdbtnOp1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbtnOp2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(pnOpt2, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(47, 47, 47)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnOpt3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(rdbtnOp3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        pnOptionsLayout.setVerticalGroup(
            pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOptionsLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnOpt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOpt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOpt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnOpt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(pnOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbtnOp0)
                    .addComponent(rdbtnOp1)
                    .addComponent(rdbtnOp2)
                    .addComponent(rdbtnOp3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pnQuestionTitle.add(pnOptions, java.awt.BorderLayout.PAGE_END);

        pnQuestion.add(pnQuestionTitle);
        pnQuestion.add(spOptions);

        pnControls.setPreferredSize(new java.awt.Dimension(980, 80));

        btnCalificar.setText("Verificar Respuesta");
        btnCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificarActionPerformed(evt);
            }
        });

        btnNext.setText("Siguiente Pregunta");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnControlsLayout = new javax.swing.GroupLayout(pnControls);
        pnControls.setLayout(pnControlsLayout);
        pnControlsLayout.setHorizontalGroup(
            pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlsLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(btnCalificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(189, 189, 189))
        );
        pnControlsLayout.setVerticalGroup(
            pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlsLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalificar)
                    .addComponent(btnNext))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnQuestion.add(pnControls);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnQuestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitleSig, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnNavM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitleSig, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(pnNavM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        makeQuestion();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificarActionPerformed
        // TODO add your handling code here:
        feedBack();
    }//GEN-LAST:event_btnCalificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificar;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup btngrpOpciones;
    private javax.swing.JLabel lblPreguntaText;
    private javax.swing.JLabel lblTitleSig;
    private javax.swing.JPanel pnControls;
    private javax.swing.JPanel pnNavM;
    private javax.swing.JPanel pnOpt0;
    private javax.swing.JPanel pnOpt1;
    private javax.swing.JPanel pnOpt2;
    private javax.swing.JPanel pnOpt3;
    private javax.swing.JPanel pnOptions;
    private javax.swing.JPanel pnQuestion;
    private javax.swing.JPanel pnQuestionTitle;
    private javax.swing.JRadioButton rdbtnOp0;
    private javax.swing.JRadioButton rdbtnOp1;
    private javax.swing.JRadioButton rdbtnOp2;
    private javax.swing.JRadioButton rdbtnOp3;
    private javax.swing.JSeparator spOptions;
    private javax.swing.JSeparator spTitle;
    // End of variables declaration//GEN-END:variables
}
