/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiador.signals;
import estudiador.common.Coordenate;
import estudiador.common.ImageHandler;
import estudiador.screens.StartScreen;
import java.awt.BorderLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;

/**
 *
 * @author Devas
 */
public class SignalSum extends javax.swing.JPanel {
    StartScreen pFrame;
    public int type;
    ArrayList<Coordenate> signalA;
    ArrayList<Coordenate> signalB;
    boolean showSum;
    boolean showResta;
    /**
     * Creates new form SignalPlay
     */
    public SignalSum(StartScreen pFrame) {
        this.pFrame = pFrame;
        initComponents();
        addMenu();
        setSins();
        type=0;
        showSum = false;
        showResta = false;
        changeSignal(0);
        updatePlot();
        
    }
    private void setSins(){
        signalA = Plotter.createSinList(1, 1, 0, 0.1);
        signalB = Plotter.createSinList(1, 1, 0, 0.1);
    }
    private void setZs(){
        signalA = Plotter.createDiscreteRandom();
        signalB = Plotter.createDiscreteRandom();
    }
    private void addMenu(){
        pnNavM.setLayout(new BorderLayout());
        pnNavM.removeAll();
        pnNavM.add(new NavMenu(pFrame));
        this.validate();
        this.repaint();
    }
    private void changeSignal(int t){
        type = t;
        pnSignalA.removeAll();
        pnSignalA.setLayout(new BorderLayout());
        pnSignalB.removeAll();
        pnSignalB.setLayout(new BorderLayout());
        if(type==0){
            pnSignalA.add(new SinSignal(this, 0));
            pnSignalB.add(new SinSignal(this, 1));
            setSins();
        }else{
            pnSignalA.add(new DiscreteSignal(this,0));
            pnSignalB.add(new DiscreteSignal(this,1));
            setZs();
        }
        updatePlot();
        revalidate();
        repaint();
    }
    public void updatePlot(){
        ArrayList<XYSeries> plot = new ArrayList();
        JPanel graph;
        
        plot.add(Plotter.createSerie(signalA, "Señal A"));
        plot.add(Plotter.createSerie(signalB, "Señal B"));
        if (type==0){
            if(showSum) plot.add(Plotter.createSerie(Plotter.createSum(signalA, signalB),"A + B"));
            if(showResta) plot.add(Plotter.createSerie(Plotter.createRest(signalA, signalB),"A - B"));
            
        }else{
            //signalA = Plotter.quickSort(signalA);
            //signalB = Plotter.quickSort(signalB);
            if(showSum) plot.add(Plotter.createSerie(Plotter.createDSum(signalA, signalB),"A + B"));
            if(showResta) plot.add(Plotter.createSerie(Plotter.createDRest(signalA, signalB),"A - B"));
        }
        graph = Plotter.createChartPanel(Plotter.createDataSet(plot),"");
        graph.setPreferredSize(pnGraphVisor.getMaximumSize());
        pnGraphVisor.removeAll();
        pnGraphVisor.setLayout(new BorderLayout());
        pnGraphVisor.add(graph);
        pnGraphVisor.revalidate();
        pnGraphVisor.repaint();
        
    }
    public void exportPlot(String route){
        ArrayList<XYSeries> plot = new ArrayList();
        BufferedImage img;
        JFreeChart graph;
        plot.add(Plotter.createSerie(signalA, "Señal A"));
        plot.add(Plotter.createSerie(signalB, "Señal B"));
        if(showSum) plot.add(Plotter.createSerie(Plotter.createSum(signalA, signalB),"A + B"));
        if(showResta) plot.add(Plotter.createSerie(Plotter.createRest(signalA, signalB),"A - B"));
        graph = Plotter.createChart(Plotter.createDataSet(plot),"");
        img = graph.createBufferedImage(1080, 720);
        try {
            ImageHandler.writeImage(img, route);
        } catch (IOException ex) {
            Logger.getLogger(SignalSum.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void setSignalA(ArrayList<Coordenate> signal){this.signalA = signal;}
    public void setSignalB(ArrayList<Coordenate> signal){this.signalB = signal;}
    public ArrayList<Coordenate> getSignalA(){return this.signalA;}
    public ArrayList<Coordenate> getSignalB(){return this.signalB;}
    public int getType(){return this.type;}
    private void setType(){this.type = type;}
   

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNavM = new javax.swing.JPanel();
        lblTitleSig = new javax.swing.JLabel();
        pnGraphVisor = new javax.swing.JPanel();
        pnSignalA = new javax.swing.JPanel();
        pnSignalB = new javax.swing.JPanel();
        pnControls = new javax.swing.JPanel();
        cboxSignal1 = new javax.swing.JComboBox<>();
        lblSignal1Box = new javax.swing.JLabel();
        tbtnAplusB = new javax.swing.JToggleButton();
        tbtnAminusB = new javax.swing.JToggleButton();
        btnSavePlot = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1000, 680));
        setMinimumSize(new java.awt.Dimension(1000, 680));
        setPreferredSize(new java.awt.Dimension(1000, 680));

        pnNavM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnNavM.setMaximumSize(new java.awt.Dimension(980, 45));
        pnNavM.setMinimumSize(new java.awt.Dimension(980, 45));
        pnNavM.setPreferredSize(new java.awt.Dimension(980, 45));

        javax.swing.GroupLayout pnNavMLayout = new javax.swing.GroupLayout(pnNavM);
        pnNavM.setLayout(pnNavMLayout);
        pnNavMLayout.setHorizontalGroup(
            pnNavMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        pnNavMLayout.setVerticalGroup(
            pnNavMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        lblTitleSig.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        lblTitleSig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleSig.setText("Módulo de Señales");

        pnGraphVisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnGraphVisor.setMaximumSize(new java.awt.Dimension(980, 345));
        pnGraphVisor.setMinimumSize(new java.awt.Dimension(980, 345));
        pnGraphVisor.setPreferredSize(new java.awt.Dimension(980, 345));

        javax.swing.GroupLayout pnGraphVisorLayout = new javax.swing.GroupLayout(pnGraphVisor);
        pnGraphVisor.setLayout(pnGraphVisorLayout);
        pnGraphVisorLayout.setHorizontalGroup(
            pnGraphVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnGraphVisorLayout.setVerticalGroup(
            pnGraphVisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
        );

        pnSignalA.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Señal A", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnSignalA.setMaximumSize(new java.awt.Dimension(310, 162));
        pnSignalA.setMinimumSize(new java.awt.Dimension(310, 162));
        pnSignalA.setPreferredSize(new java.awt.Dimension(310, 162));

        javax.swing.GroupLayout pnSignalALayout = new javax.swing.GroupLayout(pnSignalA);
        pnSignalA.setLayout(pnSignalALayout);
        pnSignalALayout.setHorizontalGroup(
            pnSignalALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        pnSignalALayout.setVerticalGroup(
            pnSignalALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnSignalB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Señal B", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnSignalB.setMaximumSize(new java.awt.Dimension(310, 162));
        pnSignalB.setMinimumSize(new java.awt.Dimension(310, 162));
        pnSignalB.setPreferredSize(new java.awt.Dimension(310, 162));

        javax.swing.GroupLayout pnSignalBLayout = new javax.swing.GroupLayout(pnSignalB);
        pnSignalB.setLayout(pnSignalBLayout);
        pnSignalBLayout.setHorizontalGroup(
            pnSignalBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        pnSignalBLayout.setVerticalGroup(
            pnSignalBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnControls.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Controles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnControls.setPreferredSize(new java.awt.Dimension(308, 162));

        cboxSignal1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sinusoidal", "Discreta" }));
        cboxSignal1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxSignal1ItemStateChanged(evt);
            }
        });

        lblSignal1Box.setText("Tipo de señales");

        tbtnAplusB.setText("A + B");
        tbtnAplusB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbtnAplusBStateChanged(evt);
            }
        });

        tbtnAminusB.setText("A - B");
        tbtnAminusB.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbtnAminusBStateChanged(evt);
            }
        });

        btnSavePlot.setText("Guardar...");
        btnSavePlot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnControlsLayout = new javax.swing.GroupLayout(pnControls);
        pnControls.setLayout(pnControlsLayout);
        pnControlsLayout.setHorizontalGroup(
            pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSignal1Box)
                    .addComponent(btnSavePlot)
                    .addComponent(cboxSignal1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtnAplusB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnAminusB, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        pnControlsLayout.setVerticalGroup(
            pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControlsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tbtnAplusB)
                    .addGroup(pnControlsLayout.createSequentialGroup()
                        .addComponent(lblSignal1Box)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxSignal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(pnControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbtnAminusB)
                    .addComponent(btnSavePlot))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnNavM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTitleSig, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnSignalA, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(pnControls, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnSignalB, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnGraphVisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitleSig, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnGraphVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnSignalA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnSignalB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnControls, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addComponent(pnNavM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboxSignal1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxSignal1ItemStateChanged
        // TODO add your handling code here:
        JComboBox cb = (JComboBox)evt.getSource();
        int selectedSignal = cb.getSelectedIndex();
        changeSignal(selectedSignal);
    }//GEN-LAST:event_cboxSignal1ItemStateChanged

    private void tbtnAplusBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbtnAplusBStateChanged
        // TODO add your handling code here:
        showSum = !showSum;
        updatePlot();
        
    }//GEN-LAST:event_tbtnAplusBStateChanged

    private void tbtnAminusBStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbtnAminusBStateChanged
        // TODO add your handling code here:
        showResta = !showResta;
        updatePlot();
    }//GEN-LAST:event_tbtnAminusBStateChanged

    private void btnSavePlotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlotActionPerformed
        // TODO add your handling code here:
        JFrame parentFrame = new JFrame();
 
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar gráfica como...");   
        fileChooser.setFileFilter(new FileNameExtensionFilter("PNG","png"));
        int userSelection = fileChooser.showSaveDialog(parentFrame);
        
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            exportPlot(fileToSave.getAbsolutePath());
        }
        
    }//GEN-LAST:event_btnSavePlotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSavePlot;
    private javax.swing.JComboBox<String> cboxSignal1;
    private javax.swing.JLabel lblSignal1Box;
    private javax.swing.JLabel lblTitleSig;
    private javax.swing.JPanel pnControls;
    private javax.swing.JPanel pnGraphVisor;
    private javax.swing.JPanel pnNavM;
    private javax.swing.JPanel pnSignalA;
    private javax.swing.JPanel pnSignalB;
    private javax.swing.JToggleButton tbtnAminusB;
    private javax.swing.JToggleButton tbtnAplusB;
    // End of variables declaration//GEN-END:variables
}
