/*
 Esta es una clase para controlar los argumentos de una función sinusoidal
 */
package estudiador.signals;

import estudiador.common.Coordenate;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Devas
 */
public class SinSignal extends javax.swing.JPanel {
    SignalSum parentPanel;
    int type;
    /**
     * Creates new form SinSignal
     */
    public SinSignal(SignalSum parentPanel, int type) {
        initComponents();
        this.parentPanel = parentPanel;
        this.type = type;
    }
    public void updateVector(){
        float a = Float.parseFloat(txtAarg.getText());
        float b = Float.parseFloat(txtBarg.getText());
        float p = Float.parseFloat(txtPhaseArg.getText());
        if(type==0)parentPanel.setSignalA(Plotter.createSinList(a, b, p, 0.1));
        else parentPanel.setSignalB(Plotter.createSinList(a, b, p, 0.1));
        parentPanel.updatePlot();
    }

    /**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAarg = new javax.swing.JTextField();
        lblSen = new javax.swing.JLabel();
        txtBarg = new javax.swing.JTextField();
        lblXarg = new javax.swing.JLabel();
        txtPhaseArg = new javax.swing.JTextField();
        lblParent = new javax.swing.JLabel();
        sldrPhase = new javax.swing.JSlider();
        lblW = new javax.swing.JLabel();
        sldrAlpha = new javax.swing.JSlider();
        lblB = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        txtAarg.setText("1");

        lblSen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSen.setText(" * Sen(");

        txtBarg.setText("1");

        lblXarg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblXarg.setText("* X + ");

        txtPhaseArg.setText("0");

        lblParent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblParent.setText(")");

        sldrPhase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldrPhaseStateChanged(evt);
            }
        });

        lblW.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblW.setText("w");

        sldrAlpha.setOrientation(javax.swing.JSlider.VERTICAL);
        sldrAlpha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldrAlphaStateChanged(evt);
            }
        });

        lblB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB.setText("B");

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTitle.setText("Señal Sinusoidal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblW, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldrPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTitle)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtAarg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblSen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtBarg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblXarg)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPhaseArg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblParent))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sldrAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSen)
                            .addComponent(txtBarg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblXarg)
                            .addComponent(txtPhaseArg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblParent))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldrPhase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblW, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sldrAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sldrPhaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldrPhaseStateChanged
        // TODO add your handling code here:
        double aux = (sldrPhase.getValue()-50)/Math.PI;
        txtPhaseArg.setText(String.valueOf(aux));
        updateVector();
    }//GEN-LAST:event_sldrPhaseStateChanged

    private void sldrAlphaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldrAlphaStateChanged
        // TODO add your handling code here:
        double aux = (sldrAlpha.getValue()-50)/2;
        txtBarg.setText(String.valueOf(aux));
        updateVector();
    }//GEN-LAST:event_sldrAlphaStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblParent;
    private javax.swing.JLabel lblSen;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblW;
    private javax.swing.JLabel lblXarg;
    private javax.swing.JSlider sldrAlpha;
    private javax.swing.JSlider sldrPhase;
    private javax.swing.JTextField txtAarg;
    private javax.swing.JTextField txtBarg;
    private javax.swing.JTextField txtPhaseArg;
    // End of variables declaration//GEN-END:variables
}
