/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estudiador.screens;
import javax.swing.JFrame;
import java.awt.Dimension;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


/**
 *
 * @author Devas
 */
public class StartScreen extends JFrame{
    private Dimension newDim=null;
    
    UIManager.LookAndFeelInfo[] lafs = UIManager.getInstalledLookAndFeels();
    
    public StartScreen() {
        initComponents();
        insertContent(new PantallaInicio(this));
        try{
            UIManager.setLookAndFeel(lafs[3].getClassName());
        }catch(Exception ex){
            ex.printStackTrace();	
        }
        SwingUtilities.updateComponentTreeUI(this);
    }
    public void insertContent(JPanel paneContent){
        this.getContentPane().removeAll();
        this.add(paneContent);
        pack();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mnuPrinc = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnitmMatrix = new javax.swing.JMenuItem();
        mnitmProgra = new javax.swing.JMenuItem();
        mnitmSignals = new javax.swing.JMenuItem();
        mnuActions = new javax.swing.JMenu();
        mnuLookandFeel = new javax.swing.JMenu();
        lookMetal = new javax.swing.JMenuItem();
        lookNimbus = new javax.swing.JMenuItem();
        lookWindC = new javax.swing.JMenuItem();
        lookWindM = new javax.swing.JMenuItem();
        lookCTIF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estudiador Inador");
        setResizable(false);

        mnuFile.setText("Archivo");

        mnitmMatrix.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mnitmMatrix.setMnemonic('M');
        mnitmMatrix.setText("Ir a Matrices");
        mnitmMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmMatrixActionPerformed(evt);
            }
        });
        mnuFile.add(mnitmMatrix);

        mnitmProgra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        mnitmProgra.setMnemonic('P');
        mnitmProgra.setText("Ir a Programación");
        mnitmProgra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmPrograActionPerformed(evt);
            }
        });
        mnuFile.add(mnitmProgra);

        mnitmSignals.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        mnitmSignals.setMnemonic('S');
        mnitmSignals.setText("Ir a Señales");
        mnitmSignals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitmSignalsActionPerformed(evt);
            }
        });
        mnuFile.add(mnitmSignals);

        mnuPrinc.add(mnuFile);

        mnuActions.setText("Acciones");
        mnuPrinc.add(mnuActions);

        mnuLookandFeel.setText("Tema Visual");

        lookMetal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        lookMetal.setText("Metal");
        lookMetal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookMetalActionPerformed(evt);
            }
        });
        mnuLookandFeel.add(lookMetal);

        lookNimbus.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        lookNimbus.setText("Nimbus (Default)");
        lookNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookNimbusActionPerformed(evt);
            }
        });
        mnuLookandFeel.add(lookNimbus);

        lookWindC.setText("Windows classic");
        lookWindC.setActionCommand("");
        lookWindC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookWindCActionPerformed(evt);
            }
        });
        mnuLookandFeel.add(lookWindC);

        lookWindM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        lookWindM.setText("Windows modern");
        lookWindM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookWindMActionPerformed(evt);
            }
        });
        mnuLookandFeel.add(lookWindM);

        lookCTIF.setText("CTIF");
        lookCTIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookCTIFActionPerformed(evt);
            }
        });
        mnuLookandFeel.add(lookCTIF);

        mnuPrinc.add(mnuLookandFeel);

        setJMenuBar(mnuPrinc);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lookMetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookMetalActionPerformed
        changeLook(0);
    }//GEN-LAST:event_lookMetalActionPerformed

    private void lookNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookNimbusActionPerformed
        changeLook(1);        // TODO add your handling code here:
    }//GEN-LAST:event_lookNimbusActionPerformed

    private void lookWindCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookWindCActionPerformed
        changeLook(4);        // TODO add your handling code here:
    }//GEN-LAST:event_lookWindCActionPerformed

    private void lookWindMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookWindMActionPerformed
        changeLook(3);        // TODO add your handling code here:
    }//GEN-LAST:event_lookWindMActionPerformed

    private void lookCTIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookCTIFActionPerformed
        changeLook(2);        // TODO add your handling code here:
    }//GEN-LAST:event_lookCTIFActionPerformed

    private void mnitmMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmMatrixActionPerformed
        // TODO add your handling code here:
        insertContent(new PantallaMatrix(this));
    }//GEN-LAST:event_mnitmMatrixActionPerformed

    private void mnitmPrograActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmPrograActionPerformed
        // TODO add your handling code here:
        insertContent(new PantallaMatrix(this));
    }//GEN-LAST:event_mnitmPrograActionPerformed

    private void mnitmSignalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitmSignalsActionPerformed
        // TODO add your handling code here:
        insertContent(new PantallaSignal(this));
    }//GEN-LAST:event_mnitmSignalsActionPerformed
    private void changeLook(int theme){
        try{
            UIManager.setLookAndFeel(lafs[theme].getClassName());
        }catch(Exception ex){
            ex.printStackTrace();	
        }
        SwingUtilities.updateComponentTreeUI(this);
        JOptionPane.showMessageDialog(this, "Has cambiado a: "+lafs[theme].getName(), "Cambio de tema", JOptionPane.INFORMATION_MESSAGE, null);
    }
    
    public static void main(String args[]) {
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
   */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartScreen ventana = new StartScreen();
                ventana.setVisible(true);
                
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem lookCTIF;
    private javax.swing.JMenuItem lookMetal;
    private javax.swing.JMenuItem lookNimbus;
    private javax.swing.JMenuItem lookWindC;
    private javax.swing.JMenuItem lookWindM;
    private javax.swing.JMenuItem mnitmMatrix;
    private javax.swing.JMenuItem mnitmProgra;
    private javax.swing.JMenuItem mnitmSignals;
    private javax.swing.JMenu mnuActions;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuLookandFeel;
    private javax.swing.JMenuBar mnuPrinc;
    // End of variables declaration//GEN-END:variables

}
